
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpdckdnrntglfxqaaifp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwZGNrZG5ybnRnbGZ4cWFhaWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5OTk3MjAsImV4cCI6MjA1NzU3NTcyMH0.2fgjrmprY6ee5mFAWQwxaB9Dm4aCmxmsVeHjoSLv4mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Check if the label column exists in pin_configs
export const checkLabelColumnExists = async (): Promise<boolean> => {
  try {
    // Use a simple query to see if the column exists
    const { data, error } = await supabase
      .from('pin_configs')
      .select('id, label')
      .limit(1);
    
    return !error;
  } catch (e) {
    console.error('Error checking label column:', e);
    return false;
  }
};

// Function to get all labels from the label table
export const fetchLabelsFromDatabase = async (): Promise<string[]> => {
  try {
    // First try to fetch directly from the label table
    const { data, error } = await supabase
      .rpc('get_labels');
      
    if (error) {
      // Try direct table access if RPC fails
      const { data: labelData, error: labelError } = await supabase
        .from('label')
        .select('name');
        
      if (labelError) {
        console.error('Error fetching labels from database:', labelError);
        return getDefaultLabels();
      }
      
      if (labelData && labelData.length > 0) {
        return labelData.map((item: any) => item.name);
      }
    } else if (data && data.length > 0) {
      return data;
    }
    
    return getDefaultLabels();
  } catch (error) {
    console.error('Error fetching labels from database:', error);
    return getDefaultLabels();
  }
};

// Function to get default labels
export const getDefaultLabels = (): string[] => {
  return ['pH', 'Suhu', 'Kelembaban', 'Pompa', 'Lampu', 'Level Air'];
};
